- name: "For Web Servers"
  hosts: myWeb
  tasks:
    - package:
        name: "httpd"
        state: present
    - copy:
        dest: "/var/www/html/index.html"
        content: "Hello! This is my Task 12.1 on AWS..!!\n"
      register: x
    - service:
        name: "httpd"
        state: restarted
        enabled: yes
      when: x.changed == true

- name: "For Load Balancer"
  hosts: myLB
  vars:
    port_no: "8080"
  tasks:
    - package:
        name: "haproxy"
        state: present

    - template:
        dest: "/etc/haproxy/haproxy.cfg"
        src: "haproxy.cfg"
      register: x

    - service:
        name: "haproxy"
        state: restarted
        enabled: yes
      when: x.changed == true

